SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS PCM_PRM_AUDIT;
DROP TABLE IF EXISTS PCM_PRM_CONTROL;
DROP TABLE IF EXISTS PCM_PRM_OBJECT;
DROP TABLE IF EXISTS PCM_PRODUCT_DATA;
DROP TABLE IF EXISTS PCM_PRODUCT_UNITS;
DROP TABLE IF EXISTS PCM_PRODUCT_GROUP;




/* Create Tables */

-- PCM_PRM_AUDIT
CREATE TABLE PCM_PRM_AUDIT
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) COMMENT '所属机构',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(100) COMMENT '参数主键',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(200) COMMENT '参数类别',
	-- ///
	-- INSERT|插入
	-- UPDATE|更新
	-- DELETE|删除
	PARAM_OPERATION VARCHAR(10) COMMENT '操作',
	OLD_OBJECT MEDIUMTEXT COMMENT '原参数值',
	NEW_OBJECT MEDIUMTEXT COMMENT '新参数值',
	UPDATE_LOG MEDIUMTEXT COMMENT '修改日志',
	MTN_USER VARCHAR(40) COMMENT '修改用户',
	JPA_TIMESTAMP DATETIME DEFAULT NOW() NOT NULL COMMENT '操作时间',
	PRIMARY KEY (ID)
) COMMENT = 'PCM_PRM_AUDIT';


-- 参数范围控制表
CREATE TABLE PCM_PRM_CONTROL
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	PARAM_CLASS VARCHAR(200) NOT NULL COMMENT '受控参数',
	PARAM_CLASS_LABEL VARCHAR(100) COMMENT '参数名称',
	PARAM_FIELD VARCHAR(50) NOT NULL COMMENT '参数属性',
	PARAM_FIELD_LABEL VARCHAR(100) COMMENT '属性名称',
	MIN_VALUE VARCHAR(20) COMMENT '最小值',
	MAX_VALUE VARCHAR(20) COMMENT '最大值',
	JAP_VERSION INT COMMENT 'JAP_VERSION',
	PRIMARY KEY (ID)
) COMMENT = '参数范围控制表';


-- PCM_PRM_OBJECT
CREATE TABLE PCM_PRM_OBJECT
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(200) NOT NULL COMMENT '参数类别',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(100) NOT NULL COMMENT '参数主键',
	PARAM_OBJECT MEDIUMTEXT NOT NULL COMMENT 'PARAM_OBJECT',
	-- ///@update
	MTN_TIMESTAMP DATETIME DEFAULT NOW() COMMENT '修改时间',
	MTN_USER VARCHAR(40) COMMENT '修改用户',
	JPA_VERSION INT COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT PARAM UNIQUE (ORG, PARAM_CLASS, PARAM_KEY)
) COMMENT = 'PCM_PRM_OBJECT';


-- 产品数据表
CREATE TABLE PCM_PRODUCT_DATA
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	PRODUCT_CODE VARCHAR(100) NOT NULL COMMENT '产品编码',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(200) NOT NULL COMMENT '参数类别',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(100) NOT NULL COMMENT '参数主键',
	CREATE_DATE DATETIME DEFAULT NOW() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
	UPDATE_USER VARCHAR(30) COMMENT '修改人',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_DATA_01 UNIQUE (ORG, PRODUCT_CODE, PARAM_CLASS, PARAM_KEY),
	CONSTRAINT UNI_PRODUCT_DATA_02 UNIQUE (ORG, UNIT_CODE, PRODUCT_CODE)
) COMMENT = '产品数据表';


-- 产品页面分组表
CREATE TABLE PCM_PRODUCT_GROUP
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	GROUP_CODE VARCHAR(32) NOT NULL COMMENT '分组编码',
	PRODUCT_TYPE VARCHAR(20) NOT NULL COMMENT '产品大类',
	GROUP_NAME VARCHAR(200) NOT NULL COMMENT '分组国际化名称',
	GROUP_NAME_CN VARCHAR(200) NOT NULL COMMENT '分组中文名称',
	GROUP_INDEX INT NOT NULL COMMENT '分组序号 ',
	-- ///
	-- @cn.sunline.pcm.definition.enums.Position
	GROUP_POSITION VARCHAR(10) COMMENT '分组位置',
	CREATE_DATE DATETIME DEFAULT NOW() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
	UPDATE_USER VARCHAR(30) COMMENT '修改人',
	JPA_VERSION INT DEFAULT 0 NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_GROUP_01 UNIQUE (ORG, GROUP_CODE)
) COMMENT = '产品页面分组表';


-- 产品页面组件表
CREATE TABLE PCM_PRODUCT_UNITS
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	GROUP_CODE VARCHAR(32) NOT NULL COMMENT '分组编码',
	UNIT_NAME VARCHAR(200) NOT NULL COMMENT '产品组件国际化名称',
	UNIT_NAME_CN VARCHAR(200) NOT NULL COMMENT '产品组件中文名称',
	UNIT_INDEX INT NOT NULL COMMENT '产品组件序号',
	-- ///
	-- @cn.sunline.common.enums.Indicator
	UNIT_REQUIRED VARCHAR(2) NOT NULL COMMENT '必配组件',
	-- ///
	-- @cn.sunline.pcm.definition.enums.ProductUnitsURL
	UNIT_MODULE VARCHAR(200) NOT NULL COMMENT '产品组件',
	UPDATE_UNITS VARCHAR(200) COMMENT '关联组件',
	CREATE_DATE DATETIME DEFAULT NOW() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
	UPDATE_USER VARCHAR(30) COMMENT '修改人',
	JPA_VERSION INT DEFAULT 0 NOT NULL COMMENT 'JPA_VERSION',
	SUB_UNIT VARCHAR(32) COMMENT '二级组件',
	-- ///
	-- @cn.sunline.pcm.definition.enums.WinSize
	UNIT_CONFIG VARCHAR(32) COMMENT '组件配置窗口',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_UNITS_01 UNIQUE (UNIT_CODE, ORG)
) COMMENT = '产品页面组件表';



