
/* Drop Tables */

DROP TABLE PCM_PRM_AUDIT CASCADE CONSTRAINTS;
DROP TABLE PCM_PRM_CONTROL CASCADE CONSTRAINTS;
DROP TABLE PCM_PRM_OBJECT CASCADE CONSTRAINTS;
DROP TABLE PCM_PRODUCT_DATA CASCADE CONSTRAINTS;
DROP TABLE PCM_PRODUCT_UNITS CASCADE CONSTRAINTS;
DROP TABLE PCM_PRODUCT_GROUP CASCADE CONSTRAINTS;




/* Create Tables */

-- PCM_PRM_AUDIT
CREATE TABLE PCM_PRM_AUDIT
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 所属机构
	ORG VARCHAR2(12),
	-- 参数主键
	PARAM_KEY VARCHAR2(100),
	-- 参数类别
	PARAM_CLASS VARCHAR2(200),
	-- 操作
	PARAM_OPERATION VARCHAR2(10),
	-- 原参数值
	OLD_OBJECT CLOB,
	-- 新参数值
	NEW_OBJECT CLOB,
	-- 修改日志
	UPDATE_LOG CLOB,
	-- 修改用户
	MTN_USER VARCHAR2(40),
	-- 操作时间
	JPA_TIMESTAMP TIMESTAMP DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);


-- 参数范围控制表
CREATE TABLE PCM_PRM_CONTROL
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 受控参数
	PARAM_CLASS VARCHAR2(200) NOT NULL,
	-- 参数名称
	PARAM_CLASS_LABEL VARCHAR2(100),
	-- 参数属性
	PARAM_FIELD VARCHAR2(50) NOT NULL,
	-- 属性名称
	PARAM_FIELD_LABEL VARCHAR2(100),
	-- 最小值
	MIN_VALUE VARCHAR2(20),
	-- 最大值
	MAX_VALUE VARCHAR2(20),
	-- JAP_VERSION
	JAP_VERSION NUMBER(10,0),
	PRIMARY KEY (ID)
);


-- PCM_PRM_OBJECT
CREATE TABLE PCM_PRM_OBJECT
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 所属机构
	ORG VARCHAR2(12) NOT NULL,
	-- 参数类别
	PARAM_CLASS VARCHAR2(200) NOT NULL,
	-- 参数主键
	PARAM_KEY VARCHAR2(100) NOT NULL,
	-- PARAM_OBJECT
	PARAM_OBJECT CLOB NOT NULL,
	-- 修改时间
	MTN_TIMESTAMP TIMESTAMP DEFAULT SYSDATE,
	-- 修改用户
	MTN_USER VARCHAR2(40),
	-- JPA_VERSION
	JPA_VERSION NUMBER(10,0),
	PRIMARY KEY (ID),
	CONSTRAINT PARAM UNIQUE (ORG, PARAM_CLASS, PARAM_KEY)
);


-- 产品数据表
CREATE TABLE PCM_PRODUCT_DATA
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 所属机构
	ORG VARCHAR2(12) NOT NULL,
	-- 产品组件编码
	UNIT_CODE VARCHAR2(32) NOT NULL,
	-- 产品编码
	PRODUCT_CODE VARCHAR2(100) NOT NULL,
	-- 参数类别
	PARAM_CLASS VARCHAR2(200) NOT NULL,
	-- 参数主键
	PARAM_KEY VARCHAR2(100) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	-- 创建人
	CREATE_USER VARCHAR2(30) NOT NULL,
	-- 修改时间
	UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
	-- 修改人
	UPDATE_USER VARCHAR2(30),
	-- JPA_VERSION
	JPA_VERSION NUMBER(10,0) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_DATA_01 UNIQUE (ORG, PRODUCT_CODE, PARAM_CLASS, PARAM_KEY),
	CONSTRAINT UNI_PRODUCT_DATA_02 UNIQUE (ORG, UNIT_CODE, PRODUCT_CODE)
);


-- 产品页面分组表
CREATE TABLE PCM_PRODUCT_GROUP
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 所属机构
	ORG VARCHAR2(12) NOT NULL,
	-- 分组编码
	GROUP_CODE VARCHAR2(32) NOT NULL,
	-- 产品大类
	PRODUCT_TYPE VARCHAR2(20) NOT NULL,
	-- 分组国际化名称
	GROUP_NAME VARCHAR2(200) NOT NULL,
	-- 分组中文名称
	GROUP_NAME_CN VARCHAR2(200) NOT NULL,
	-- 分组序号 
	GROUP_INDEX NUMBER(10,0) NOT NULL,
	-- 分组位置
	GROUP_POSITION VARCHAR2(10),
	-- 创建时间
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	-- 创建人
	CREATE_USER VARCHAR2(30) NOT NULL,
	-- 修改时间
	UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
	-- 修改人
	UPDATE_USER VARCHAR2(30),
	-- JPA_VERSION
	JPA_VERSION NUMBER(10,0) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_GROUP_01 UNIQUE (ORG, GROUP_CODE)
);


-- 产品页面组件表
CREATE TABLE PCM_PRODUCT_UNITS
(
	-- ID
	ID VARCHAR2(32) NOT NULL,
	-- 所属机构
	ORG VARCHAR2(12) NOT NULL,
	-- 产品组件编码
	UNIT_CODE VARCHAR2(32) NOT NULL,
	-- 分组编码
	GROUP_CODE VARCHAR2(32) NOT NULL,
	-- 产品组件国际化名称
	UNIT_NAME VARCHAR2(200) NOT NULL,
	-- 产品组件中文名称
	UNIT_NAME_CN VARCHAR2(200) NOT NULL,
	-- 产品组件序号
	UNIT_INDEX NUMBER(10,0) NOT NULL,
	-- 必配组件
	UNIT_REQUIRED VARCHAR2(2) NOT NULL,
	-- 产品组件
	UNIT_MODULE VARCHAR2(200) NOT NULL,
	-- 关联组件
	UPDATE_UNITS VARCHAR2(200),
	-- 创建时间
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	-- 创建人
	CREATE_USER VARCHAR2(30) NOT NULL,
	-- 修改时间
	UPDATE_DATE TIMESTAMP DEFAULT SYSDATE,
	-- 修改人
	UPDATE_USER VARCHAR2(30),
	-- JPA_VERSION
	JPA_VERSION NUMBER(10,0) DEFAULT 0 NOT NULL,
	-- 二级组件
	SUB_UNIT VARCHAR2(32),
	-- 组件配置窗口
	UNIT_CONFIG VARCHAR2(32),
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_UNITS_01 UNIQUE (UNIT_CODE, ORG)
);



/* Comments */

COMMENT ON TABLE PCM_PRM_AUDIT IS 'PCM_PRM_AUDIT';
COMMENT ON COLUMN PCM_PRM_AUDIT.ID IS 'ID';
COMMENT ON COLUMN PCM_PRM_AUDIT.ORG IS '所属机构';
COMMENT ON COLUMN PCM_PRM_AUDIT.PARAM_KEY IS '参数主键';
COMMENT ON COLUMN PCM_PRM_AUDIT.PARAM_CLASS IS '参数类别';
COMMENT ON COLUMN PCM_PRM_AUDIT.PARAM_OPERATION IS '操作';
COMMENT ON COLUMN PCM_PRM_AUDIT.OLD_OBJECT IS '原参数值';
COMMENT ON COLUMN PCM_PRM_AUDIT.NEW_OBJECT IS '新参数值';
COMMENT ON COLUMN PCM_PRM_AUDIT.UPDATE_LOG IS '修改日志';
COMMENT ON COLUMN PCM_PRM_AUDIT.MTN_USER IS '修改用户';
COMMENT ON COLUMN PCM_PRM_AUDIT.JPA_TIMESTAMP IS '操作时间';
COMMENT ON TABLE PCM_PRM_CONTROL IS '参数范围控制表';
COMMENT ON COLUMN PCM_PRM_CONTROL.ID IS 'ID';
COMMENT ON COLUMN PCM_PRM_CONTROL.PARAM_CLASS IS '受控参数';
COMMENT ON COLUMN PCM_PRM_CONTROL.PARAM_CLASS_LABEL IS '参数名称';
COMMENT ON COLUMN PCM_PRM_CONTROL.PARAM_FIELD IS '参数属性';
COMMENT ON COLUMN PCM_PRM_CONTROL.PARAM_FIELD_LABEL IS '属性名称';
COMMENT ON COLUMN PCM_PRM_CONTROL.MIN_VALUE IS '最小值';
COMMENT ON COLUMN PCM_PRM_CONTROL.MAX_VALUE IS '最大值';
COMMENT ON COLUMN PCM_PRM_CONTROL.JAP_VERSION IS 'JAP_VERSION';
COMMENT ON TABLE PCM_PRM_OBJECT IS 'PCM_PRM_OBJECT';
COMMENT ON COLUMN PCM_PRM_OBJECT.ID IS 'ID';
COMMENT ON COLUMN PCM_PRM_OBJECT.ORG IS '所属机构';
COMMENT ON COLUMN PCM_PRM_OBJECT.PARAM_CLASS IS '参数类别';
COMMENT ON COLUMN PCM_PRM_OBJECT.PARAM_KEY IS '参数主键';
COMMENT ON COLUMN PCM_PRM_OBJECT.PARAM_OBJECT IS 'PARAM_OBJECT';
COMMENT ON COLUMN PCM_PRM_OBJECT.MTN_TIMESTAMP IS '修改时间';
COMMENT ON COLUMN PCM_PRM_OBJECT.MTN_USER IS '修改用户';
COMMENT ON COLUMN PCM_PRM_OBJECT.JPA_VERSION IS 'JPA_VERSION';
COMMENT ON TABLE PCM_PRODUCT_DATA IS '产品数据表';
COMMENT ON COLUMN PCM_PRODUCT_DATA.ID IS 'ID';
COMMENT ON COLUMN PCM_PRODUCT_DATA.ORG IS '所属机构';
COMMENT ON COLUMN PCM_PRODUCT_DATA.UNIT_CODE IS '产品组件编码';
COMMENT ON COLUMN PCM_PRODUCT_DATA.PRODUCT_CODE IS '产品编码';
COMMENT ON COLUMN PCM_PRODUCT_DATA.PARAM_CLASS IS '参数类别';
COMMENT ON COLUMN PCM_PRODUCT_DATA.PARAM_KEY IS '参数主键';
COMMENT ON COLUMN PCM_PRODUCT_DATA.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN PCM_PRODUCT_DATA.CREATE_USER IS '创建人';
COMMENT ON COLUMN PCM_PRODUCT_DATA.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN PCM_PRODUCT_DATA.UPDATE_USER IS '修改人';
COMMENT ON COLUMN PCM_PRODUCT_DATA.JPA_VERSION IS 'JPA_VERSION';
COMMENT ON TABLE PCM_PRODUCT_GROUP IS '产品页面分组表';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.ID IS 'ID';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.ORG IS '所属机构';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.GROUP_CODE IS '分组编码';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.PRODUCT_TYPE IS '产品大类';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.GROUP_NAME IS '分组国际化名称';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.GROUP_NAME_CN IS '分组中文名称';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.GROUP_INDEX IS '分组序号 ';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.GROUP_POSITION IS '分组位置';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.CREATE_USER IS '创建人';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.UPDATE_USER IS '修改人';
COMMENT ON COLUMN PCM_PRODUCT_GROUP.JPA_VERSION IS 'JPA_VERSION';
COMMENT ON TABLE PCM_PRODUCT_UNITS IS '产品页面组件表';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.ID IS 'ID';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.ORG IS '所属机构';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_CODE IS '产品组件编码';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.GROUP_CODE IS '分组编码';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_NAME IS '产品组件国际化名称';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_NAME_CN IS '产品组件中文名称';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_INDEX IS '产品组件序号';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_REQUIRED IS '必配组件';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_MODULE IS '产品组件';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UPDATE_UNITS IS '关联组件';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.CREATE_USER IS '创建人';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UPDATE_USER IS '修改人';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.JPA_VERSION IS 'JPA_VERSION';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.SUB_UNIT IS '二级组件';
COMMENT ON COLUMN PCM_PRODUCT_UNITS.UNIT_CONFIG IS '组件配置窗口';



