SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS PCM_ORG_PARAMETTER;
DROP TABLE IF EXISTS PCM_PARAMETER_ORDER;
DROP TABLE IF EXISTS PCM_PRM_AUDIT;
DROP TABLE IF EXISTS PCM_PRM_CONTROL;
DROP TABLE IF EXISTS PCM_PRM_OBJECT;
DROP TABLE IF EXISTS PCM_PRODUCT_DATA;
DROP TABLE IF EXISTS PCM_PRODUCT_UNITS;
DROP TABLE IF EXISTS PCM_PRODUCT_GROUP;
DROP TABLE IF EXISTS PCM_PRODUCT_REL;
DROP TABLE IF EXISTS PCM_PRODUCT_UNIT;




/* Create Tables */

-- 机构参数表
CREATE TABLE PCM_ORG_PARAMETTER
(
	ORG_CODE VARCHAR(100) NOT NULL COMMENT '机构编码',
	ORG_NAME VARCHAR(32) COMMENT '机构名称',
	ORG_ADDRESS VARCHAR(32) COMMENT '机构地址',
	ORG_LEVEL VARCHAR(32) COMMENT '机构级别',
	PARENT_ORG_CODE VARCHAR(32) COMMENT '上级机构编码',
	ORG_CONTACT_PHONE VARCHAR(32) COMMENT '机构联系电话',
	PRIMARY KEY (ORG_CODE)
) COMMENT = '机构参数表';


-- 参数展示字段自定义排序
CREATE TABLE PCM_PARAMETER_ORDER
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	-- 参数全类名
	PARAM_CLASS VARCHAR(100) NOT NULL COMMENT '参数全类名',
	-- 字段名称
	FILED_NAME VARCHAR(100) NOT NULL COMMENT '字段名字',
	ORDER_INDEX VARCHAR(100) NOT NULL COMMENT '排序',
	ORG_CODE VARCHAR(100) COMMENT '机构编码',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID)
) COMMENT = '参数展示字段自定义排序';


-- PCM_PRM_AUDIT
CREATE TABLE PCM_PRM_AUDIT
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) COMMENT '所属机构',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(64) COMMENT '参数主键',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(128) COMMENT '参数类别',
	-- ///@EnumGen
	-- INSERT|插入
	-- UPDATE|更新
	-- DELETE|删除
	PARAM_OPERATION VARCHAR(10) COMMENT '操作',
	OLD_OBJECT MEDIUMTEXT COMMENT '原参数值',
	NEW_OBJECT MEDIUMTEXT COMMENT '新参数值',
	UPDATE_LOG MEDIUMTEXT COMMENT '修改日志',
	MTN_USER VARCHAR(40) COMMENT '修改用户',
	JPA_TIMESTAMP DATETIME DEFAULT NOW(), SYSDATE() NOT NULL COMMENT '操作时间',
	PRIMARY KEY (ID)
) COMMENT = 'PCM_PRM_AUDIT';


-- 参数范围控制表
CREATE TABLE PCM_PRM_CONTROL
(
	-- ///@UuidSeq
	PID VARCHAR(32) NOT NULL COMMENT 'PID',
	PARAM_CLASS VARCHAR(200) NOT NULL COMMENT '受控参数',
	PARAM_CLASS_LABEL VARCHAR(100) COMMENT '参数名称',
	PARAM_FIELD VARCHAR(50) NOT NULL COMMENT '参数属性',
	PARAM_FIELD_LABEL VARCHAR(100) COMMENT '属性名称',
	MIN_VALUE VARCHAR(20) COMMENT '最小值',
	MAX_VALUE VARCHAR(20) COMMENT '最大值',
	JPA_VERSION INT COMMENT 'JPA_VERSION',
	PRIMARY KEY (PID)
) COMMENT = '参数范围控制表';


-- PCM_PRM_OBJECT
CREATE TABLE PCM_PRM_OBJECT
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(128) NOT NULL COMMENT '参数类别',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(64) NOT NULL COMMENT '参数主键',
	PARAM_OBJECT MEDIUMTEXT NOT NULL COMMENT 'PARAM_OBJECT',
	-- ///@create
	CREATE_TIME DATETIME COMMENT '创建时间',
	CREATE_USER VARCHAR(30) COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT PARAM UNIQUE (ORG, PARAM_CLASS, PARAM_KEY)
) COMMENT = 'PCM_PRM_OBJECT';


-- 产品数据表
CREATE TABLE PCM_PRODUCT_DATA
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	PRODUCT_CODE VARCHAR(100) NOT NULL COMMENT '产品编码',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(128) NOT NULL COMMENT '参数类别',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(64) NOT NULL COMMENT '参数主键',
	-- ///@create
	CREATE_TIME DATETIME DEFAULT NOW(), SYSDATE() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME DEFAULT NOW(), SYSDATE() COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_DATA_01 UNIQUE (ORG, PRODUCT_CODE, PARAM_CLASS, PARAM_KEY),
	CONSTRAINT UNI_PRODUCT_DATA_02 UNIQUE (ORG, UNIT_CODE, PRODUCT_CODE)
) COMMENT = '产品数据表';


-- 产品页面分组表
CREATE TABLE PCM_PRODUCT_GROUP
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	-- 父节点代码
	PRODUCT_PARENT_ID VARCHAR(100) NOT NULL COMMENT '父节点代码',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	GROUP_CODE VARCHAR(32) NOT NULL COMMENT '分组编码',
	PRODUCT_TYPE VARCHAR(20) NOT NULL COMMENT '产品大类',
	GROUP_NAME VARCHAR(200) NOT NULL COMMENT '分组国际化名称',
	NAME VARCHAR(200) NOT NULL COMMENT '分组中文名称',
	GROUP_INDEX INT NOT NULL COMMENT '分组序号 ',
	-- ///@EnumRef:cn.sunline.pcm.definition.enums.Position
	-- TOP|上
	-- BOTTOM|下
	-- LEFT|左
	-- RIGHT|右
	-- CENTER|中
	GROUP_POSITION VARCHAR(10) COMMENT '分组位置',
	-- ///@create
	CREATE_TIME DATETIME DEFAULT NOW(), SYSDATE() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME DEFAULT NOW(), SYSDATE() COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT DEFAULT 0 NOT NULL COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_GROUP_01 UNIQUE (ORG, GROUP_CODE)
) COMMENT = '产品页面分组表';


-- 产品数据关联表
CREATE TABLE PCM_PRODUCT_REL
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	PRODUCT_CODE VARCHAR(100) NOT NULL COMMENT '产品编码',
	-- 参数类别，使用参数类对应的全名来区分
	PARAM_CLASS VARCHAR(128) NOT NULL COMMENT '参数类别',
	-- 参数主键，可以为空，表示机构级全局参数
	PARAM_KEY VARCHAR(64) NOT NULL COMMENT '参数主键',
	PARENT_ID VARCHAR(32) COMMENT '父ID',
	PARENT_PARAM_CLASS VARCHAR(200) COMMENT '父参数类型',
	PARENT_PARAM_KEY VARCHAR(100) COMMENT '父参数主键',
	-- ///@create
	CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID)
) COMMENT = '产品数据关联表';


-- 产品组件表
CREATE TABLE PCM_PRODUCT_UNIT
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	-- 产品组件所属分组
	PRODUCT_UNIT_GROUP VARCHAR(100) NOT NULL COMMENT '产品组件所属分组',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	-- ///@EnumRef:cn.sunline.ppy.dictionary.enums.ProductType
	-- A|传统贷款产品
	-- C|信用卡产品
	-- 
	-- D|借记卡产品
	-- 
	-- M|互联网贷款产品
	-- 
	-- S|小微贷款产品
	PRODUCT_TYPE VARCHAR(32) NOT NULL COMMENT '产品类型',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	UNIT_MODULE VARCHAR(30) NOT NULL COMMENT '产品组件类型',
	UNIT_NAME VARCHAR(200) NOT NULL COMMENT '产品组件国际化名称',
	UNIT_NAME_CN VARCHAR(200) COMMENT '产品组件中文名称',
	-- ///@EnumRef:cn.sunline.common.enums.Indicator
	-- Y|是
	-- N|否
	MULTIPLE VARCHAR(1) COMMENT '是否允许多选',
	UNIT_INDEX INT NOT NULL COMMENT '产品组件序号',
	UNIT_RELATIONS TEXT COMMENT '关联组件',
	-- ///@create
	CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT DEFAULT 0 COMMENT 'JPA_VERSION',
	PRIMARY KEY (ID),
	CONSTRAINT IDX_PCM_PRODUCT_UNIT_01 UNIQUE (ORG, PRODUCT_TYPE, UNIT_CODE)
) COMMENT = '产品组件表';


-- 产品页面组件表
CREATE TABLE PCM_PRODUCT_UNITS
(
	-- ///@UuidSeq
	ID VARCHAR(32) NOT NULL COMMENT 'ID',
	ORG VARCHAR(12) NOT NULL COMMENT '所属机构',
	UNIT_CODE VARCHAR(32) NOT NULL COMMENT '产品组件编码',
	GROUP_CODE VARCHAR(32) NOT NULL COMMENT '分组编码',
	UNIT_NAME VARCHAR(200) NOT NULL COMMENT '产品组件国际化名称',
	UNIT_NAME_CN VARCHAR(200) NOT NULL COMMENT '产品组件中文名称',
	UNIT_INDEX INT NOT NULL COMMENT '产品组件序号',
	-- ///@EnumRef:cn.sunline.common.enums.Indicator
	-- Y|是
	-- N|否
	UNIT_REQUIRED VARCHAR(2) NOT NULL COMMENT '必配组件',
	-- ///@EnumRef:cn.sunline.pcm.definition.enums.ProductUnitsURL
	-- PHYCARD|卡片代码
	-- OVERLIMIT|超限费
	-- MSG|短信模板
	-- CUS|客服服务费用
	-- FEE|杂项费用
	-- LATEFEE|滞纳金信息
	-- CRE|账户定义信息
	-- TXNFEE|交易费用
	-- LOAN|贷款产品
	-- LOANTERM|贷款产品子产品
	-- CREDITPLAN|信用计划产品
	-- FINANCYORG|合作机构
	-- DEBIT|存款产品
	-- DEBITACCT|存款账号
	-- DEBYACCT|存款子账号
	UNIT_MODULE VARCHAR(200) NOT NULL COMMENT '产品组件',
	UPDATE_UNITS VARCHAR(200) COMMENT '关联组件',
	-- ///@create
	CREATE_TIME DATETIME DEFAULT NOW(), SYSDATE() NOT NULL COMMENT '创建时间',
	CREATE_USER VARCHAR(30) NOT NULL COMMENT '创建人',
	-- ///@update
	LST_UPD_TIME DATETIME DEFAULT NOW(), SYSDATE() COMMENT '最后修改时间',
	LST_UPD_USER VARCHAR(30) COMMENT '最后修改人',
	JPA_VERSION INT DEFAULT 0 NOT NULL COMMENT 'JPA_VERSION',
	SUB_UNIT VARCHAR(32) COMMENT '二级组件',
	-- ///@EnumRef:cn.sunline.pcm.definition.enums.WinSize
	-- M|中窗口
	-- B|大窗口
	-- S|小窗口
	UNIT_CONFIG VARCHAR(32) COMMENT '组件配置窗口',
	PRIMARY KEY (ID),
	CONSTRAINT UNI_PRODUCT_UNITS_01 UNIQUE (UNIT_CODE, ORG)
) COMMENT = '产品页面组件表';



