dcn: T134505762
spring:
  application:
    name: ${dcn}-pcm-surface-impl
    
server:
  port: 8103
eureka:
  instance: 
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.186.65.98:31001/eureka/,http://10.186.65.99:31001/eureka/,http://10.186.65.100:31001/eureka/
logging: 
  config: classpath:config/log4j2.xml