dcn: T134505762
spring:
  application:
    name: ${dcn}-pcm-surface-impl
    
server:
  port: 8190
eureka:
  instance: 
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
logging: 
  config: classpath:config/log4j2.xml